version: '3.8'
services:
  highload-service:
    image: se7go/highload-y25-service:4.05
    environment:
      - STORAGE_COMPONENT=redis
      - HIGHLOAD_SERVICE_PORT=8080

      - HIGHLOAD_STORAGE_PATH=./storage
      - SS_TABLE_SEGMENT_SIZE_KIB=4
      - SS_TABLE_MERGED_SIZE_MIB=1
      - MEM_TABLE_SIZE_MIB=1

      - HIGHLOAD_MONGO_DB_IP=mongo-db
      - HIGHLOAD_MONGO_DB_PORT=27017
      - HIGHLOAD_MONGO_DB_NAME=keyValueDb
      - HIGHLOAD_MONGO_DB_USERNAME=highload
      - HIGHLOAD_MONGO_DB_PASSWORD=12345

#      - REDIS_USERNAME=highload
      - REDIS_PASSWORD=12345
      - REDIS_MASTER_A_IP=10.5.1.10:7000
      - REDIS_MASTER_B_IP=10.5.1.11:7001
      - REDIS_MASTER_C_IP=10.5.1.12:7002
      - REDIS_SLAVE_A_IP=10.5.1.13:7003
      - REDIS_SLAVE_B_IP=10.5.1.14:7004
      - REDIS_SLAVE_C_IP=10.5.1.15:7005
      - REDIS_NODES=

    container_name: highload-service-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.2
    volumes:
      - ./storage/:/app/storage
  mongo-db:
    image: mongo:latest
    container_name: mongo-db-container
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=highload
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_INITDB_DATABASE=keyValueDb
    ports:
        - "27018:27017"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.3

  redis-master:
    image: redis:latest
    container_name: redis-db-master-container
    restart: unless-stopped
    environment:
      REDIS_MASTER_PORT: 6380
      REDIS_CONF_PATH: /app/redis.conf
      REDIS_PASSWORD: 12345
    volumes:
      - ./redis_generate_conf/:/app/generate
    command: >
      /bin/bash /app/generate/redis-master-conf.sh
    ports:
      - "6380:6380"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.4

  redis-slave1:
    image: redis:latest
    container_name: redis-db-slave1-container
    ports:
      - "6381:6381"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.5
    environment:
      REDIS_CONF_PATH: /app/redis.conf
      REDIS_PASSWORD: 12345
      REDIS_SLAVE1_PORT: 6381
      REDIS_MASTER_PASSWORD: 12345
      REDIS_MASTER_IP: 10.5.0.4
      REDIS_MASTER_PORT: 6380
    volumes:
      - ./redis_generate_conf/:/app/generate
    command: >
      /bin/bash /app/generate/redis-slave1-conf.sh
    depends_on:
      - redis-master

  redis-slave2:
    image: redis:latest
    container_name: redis-db-slave2-container
#    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6382 --slaveof 10.5.0.4 6380 --read-only yes
    ports:
      - "6382:6382"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.6
    environment:
      REDIS_CONF_PATH: /app/generate/redis.conf
      REDIS_PASSWORD: 12345
      REDIS_SLAVE2_PORT: 6381
      REDIS_MASTER_PASSWORD: 12345
      REDIS_MASTER_IP: 10.5.0.4
      REDIS_MASTER_PORT: 6380
    volumes:
      - ./redis_generate_conf/:/app/generate
    command: >
      /bin/bash /app/generate/redis-slave2-conf.sh
    depends_on:
      - redis-master

  highload-client:
    image: se7go/highload-y25-client:2.99
    environment:
      - HIGHLOAD_SERVICE_IP=highload-service
      - HIGHLOAD_SERVICE_PORT=8080
    container_name: highload-client-container
    command: set key13 123
    #--logic=test
    networks:
      - highload-network-bridge


networks:
  highload-network-bridge:
    name: highload-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
  highload-network-host:
    name: highload-network-host
    driver: host
volumes:
  redis_data: { }
  storage: { }