version: '3.8'
services:
  highload-service:
    image: se7go/highload-y25-service:4.07
    environment:
      - STORAGE_COMPONENT=lsm
      - HIGHLOAD_SERVICE_PORT=8080

      - HIGHLOAD_STORAGE_PATH=/app/storage
      - SS_TABLE_SEGMENT_SIZE_KIB=4
      - SS_TABLE_MERGED_SIZE_MIB=1
      - MEM_TABLE_SIZE_MIB=1

      - HIGHLOAD_MONGO_DB_IP=mongo-db
      - HIGHLOAD_MONGO_DB_PORT=27017
      - HIGHLOAD_MONGO_DB_NAME=keyValueDb
      - HIGHLOAD_MONGO_DB_USERNAME=highload
      - HIGHLOAD_MONGO_DB_PASSWORD=12345


      - REDIS_PASSWORD=12345
#      - REDIS_HOST=redis-slave1
#      - REDIS_PORT=6380
      - REDIS_NODES=10.5.1.10:7000,10.5.1.11:7001,10.5.1.12:7002,10.5.1.13:7003,10.5.1.14:7004,10.5.1.15:7005

    container_name: highload-service-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.2
    volumes:
      - ./volumes/storage/:/app/storage
  mongo-db:
    image: mongo:latest
    container_name: mongo-db-container
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=highload
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_INITDB_DATABASE=keyValueDb
    ports:
        - "27018:27017"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.3

  redis-master:
    image: redis:latest
    container_name: redis-db-master-container
    restart: unless-stopped
    environment:
      REDIS_MASTER_PORT: 6380
      REDIS_CONF_PATH: /app/redis.conf
      REDIS_PASSWORD: 12345
    volumes:
      - ./volumes/redis_generate_conf/:/app/generate
    command: >
      /bin/bash /app/generate/redis-master-conf.sh
    ports:
      - "6380:6380"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.4

  redis-slave1:
    image: redis:latest
    container_name: redis-db-slave1-container
    ports:
      - "6381:6381"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.5
    environment:
      REDIS_CONF_PATH: /app/redis.conf
      REDIS_PASSWORD: 12345
      REDIS_SLAVE_PORT: 6381
      REDIS_MASTER_PASSWORD: 12345
      REDIS_MASTER_IP: 10.5.0.4
      REDIS_MASTER_PORT: 6380
    volumes:
      - ./volumes/redis_generate_conf/:/app/generate
    command: >
      /bin/bash /app/generate/redis-slave-conf.sh
    depends_on:
      - redis-master

  redis-slave2:
    image: redis:latest
    container_name: redis-db-slave2-container
    ports:
      - "6382:6382"
    networks:
      highload-network-bridge:
        ipv4_address: 10.5.0.6
    environment:
      REDIS_CONF_PATH: /app/generate/redis.conf
      REDIS_PASSWORD: 12345
      REDIS_SLAVE_PORT: 6381
      REDIS_MASTER_PASSWORD: 12345
      REDIS_MASTER_IP: 10.5.0.4
      REDIS_MASTER_PORT: 6380
    volumes:
      - ./volumes/redis_generate_conf/:/app/generate
    command: >
      /bin/bash /app/generate/redis-slave-conf.sh
    depends_on:
      - redis-master

  highload-client:
    image: se7go/highload-y25-client:2.99
    environment:
      - HIGHLOAD_SERVICE_IP=highload-service
      - HIGHLOAD_SERVICE_PORT=8080
    container_name: highload-client-container
    command: set key13 123
    networks:
      - highload-network-bridge


networks:
  highload-network-bridge:
    name: highload-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
  highload-network-host:
    name: highload-network-host
    driver: host
